server:
  port: 6600
spring:
  application:
    name: nacos-provider-movie6600
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848 #nacos服务器地址
    sentinel:
      transport:
        #sentinel控制台和当前应用进行数据传递的端口号
        port: 8719
        #当前应用连接的sentinel控制台
        dashboard: localhost:8080